modules/admin/models/Movie.php
<?php

namespace app\modules\admin\models;

/**
 * This is the model class for table "movies".
 *
 * @property int $id
 * @property string $name
 * @property string $genre
 * @property string $country
 * @property string $duration
 * @property string $director
 * @property string|null $actors
 * @property string $release_date
 * @property string $description
 * @property int $status
 * @property string $images_path
 *
 * @property Show[] $shows
 */
class Movie extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'movies';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['name', 'genre', 'country', 'duration', 'director', 'release_date', 'description', 'status', 'images_path'], 'required'],
            [['description'], 'string'],
            [['status'], 'integer'],
            [['name', 'director'], 'string', 'max' => 45],
            [['genre', 'actors', 'images_path'], 'string', 'max' => 100],
            [['duration'], 'string', 'max' => 5],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'Идентификатор',
            'name' => 'Название',
            'genre' => 'Жанр',
            'country' => 'Страна',
            'duration' => 'Длительность',
            'director' => 'Режиссер',
            'actors' => 'В ролях',
            'release_date' => 'Дата выхода',
            'description' => 'Описание',
            'status' => 'Статус',
            'images_path' => 'Путь к изображениям',
        ];
    }

    /**
     * Gets query for Shows.
     *
     * @return \yii\db\ActiveQuery
     */
    public function getShows()
    {
        return $this->hasMany(Show::class, ['movie_id' => 'id']);
    }

    /**
     * Возвращает кол-во записей
     *
     * @param array $params
     * @return int|string
     */
    public static function getCount($params = [])
    {
        return static::find()->where($params)->count();
    }
}

modules/admin/controllers/MovieController.php
<?php

namespace app\modules\admin\controllers;

use Yii;
use app\modules\admin\models\MovieForm;
use app\modules\admin\models\Movie;
use app\modules\admin\models\MovieSearch;
use yii\web\Controller;
use yii\web\ForbiddenHttpException;
use yii\web\NotFoundHttpException;
use yii\web\UploadedFile;

/**
 * MovieController implements the CRUD actions for Movie model.
 */
class MovieController extends Controller
{
    /**
     * Lists all Movie models.
     * @return string
     * @throws ForbiddenHttpException
     * @throws \yii\base\InvalidConfigException
     */
    public function actionIndex()
    {
        if (!$this->getUser()->can('listMovies')) {
            throw new ForbiddenHttpException('Недостаточно прав');
        }

        $searchModel = new MovieSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Movie model.
     * @param integer $id
     * @return string
     * @throws ForbiddenHttpException
     * @throws NotFoundHttpException
     * @throws \yii\base\InvalidConfigException
     */
    public function actionView($id)
    {
        if (!$this->getUser()->can('viewMovie')) {
            throw new ForbiddenHttpException('Недостаточно прав');
        }

        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * @return string|\yii\web\Response
     * @throws \yii\base\Exception
     */
    public function actionCreate()
    {
        if (!$this->getUser()->can('createMovie')) {
            throw new ForbiddenHttpException('Недостаточно прав');
        }

        $model = new MovieForm(['scenario' => 'create']);

        if ($model->load(Yii::$app->request->post())) {
            $model->poster = UploadedFile::getInstance($model, 'poster');
            $model->movie_shots = UploadedFile::getInstances($model, 'movie_shots');
            $model->trailer = UploadedFile::getInstance($model, 'trailer');

            if ($movie = $model->create()) {
                Yii::$app->session->setFlash('success', 'Запись сохранена');
                return $this->redirect(['view', 'id' => $movie->id]);
            }
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Movie model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return string|\yii\web\Response
     * @throws ForbiddenHttpException
     * @throws \yii\base\ErrorException
     * @throws \yii\base\Exception
     */
    public function actionUpdate($id)
    {
        if (!$this->getUser()->can('updateMovie')) {
            throw new ForbiddenHttpException('Недостаточно прав');
        }

        $model = new MovieForm(['id' => $id]);

        if ($model->load(Yii::$app->request->post())) {
            $model->poster = UploadedFile::getInstance($model, 'poster');
            $model->movie_shots = UploadedFile::getInstances($model, 'movie_shots');
            $model->trailer = UploadedFile::getInstance($model, 'trailer');

            if ($model->update()) {
                Yii::$app->session->setFlash('success', 'Запись сохранена');
                return $this->redirect(['view', 'id' => $model->id]);
            }
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * @return string
     * @throws ForbiddenHttpException
     * @throws \yii\base\InvalidConfigException
     */
    public function actionDelete()
    {
        if ($this->getUser()->isGuest) {
            throw new ForbiddenHttpException('Недостаточно прав');
        }
        $filePath = Yii::$app->request->post('key');
        unlink($filePath);
        return '{}';
    }

    /**
     * Finds the Movie model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Movie the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Movie::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('Страница не найдена.');
    }

    /**
     * @return null|object
     * @throws \yii\base\InvalidConfigException
     */
    private function getUser()
    {
        return Yii::$app->getModule('admin')->get('user');
    }
}

modules/admin/controllers/ShowController.php
<?php

namespace app\modules\admin\controllers;

use Yii;
use app\modules\admin\models\Show;
use app\modules\admin\models\ShowSearch;
use yii\web\Controller;
use yii\web\ForbiddenHttpException;
use yii\web\NotFoundHttpException;

/**
 * ShowController реализует действия CRUD для модели Show.
 */
class ShowController extends Controller
{
    /**
     * Отображает страницу со списком Киносеансов.
     * @return string
     * @throws ForbiddenHttpException
     * @throws \yii\base\InvalidConfigException
     */
    public function actionIndex()
    {
        if (!$this->getUser()->can('listShows')) {
            throw new ForbiddenHttpException('Недостаточно прав');
        }

        $searchModel = new ShowSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Отображает страницу с выбранным Киносеансом.
     * @param integer $id
     * @return string
     * @throws ForbiddenHttpException
     * @throws NotFoundHttpException
     * @throws \yii\base\InvalidConfigException
     */
    public function actionView($id)
    {
        if (!$this->getUser()->can('viewShow')) {
            throw new ForbiddenHttpException('Недостаточно прав');
        }

        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Отображает страницу с формой создания Киносеанса.
     * Если создание произошло успешно, то перенаправит на страницу просмотра.
     * @return string|\yii\web\Response
     * @throws ForbiddenHttpException
     * @throws \yii\base\InvalidConfigException
     */
    public function actionCreate()
    {
        if (!$this->getUser()->can('createShow')) {
            throw new ForbiddenHttpException('Недостаточно прав');
        }

        $model = new Show();
        $model->movie_id = Yii::$app->request->post("movieID");

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            Yii::$app->session->setFlash('success', 'Запись сохранена');
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Отображает страницу с формой редактирования Киносеанса.
     * Если обновление произошло успешно, то перенаправит на страницу просмотра.
     * @param integer $id
     * @return string|\yii\web\Response
     * @throws ForbiddenHttpException
     * @throws NotFoundHttpException
     * @throws \yii\base\InvalidConfigException
     */
    public function actionUpdate($id)
    {
        if (!$this->getUser()->can('updateShow')) {
            throw new ForbiddenHttpException('Недостаточно прав');
        }

        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            Yii::$app->session->setFlash('success', 'Запись сохранена');
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Ищет модель Show по $id.
     * Если модель не найдена, то будет выдано исключение 404 HTTP.
     * @param integer $id
     * @return Show the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Show::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('Страница не найдена.');
    }

    /**
     * @return null|object
     * @throws \yii\base\InvalidConfigException
     */
    private function getUser()
    {
        return Yii::$app->getModule('admin')->get('user');
    }
}

modules/admin/views/movie/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\date\DatePicker;
use kartik\select2\Select2;
use kartik\file\FileInput;

/* @var $this yii\web\View */
/* @var $model app\modules\admin\models\MovieForm */
/* @var $form yii\widgets\ActiveForm */
/* @var $isUpdate boolean */

if (!isset($isUpdate)) {
    $isUpdate = false;
}
?>

<div class="movie-form">

    <?php $form = ActiveForm::begin(['options' => ['enctype' => 'multipart/form-data', 'data-pjax' => true]]); ?>

    <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'oldName')->hiddenInput()->label(false) ?>

    <?= $form->field($model, 'genre')->widget(Select2::class, [
        'name' => 'genre',
        'data' => \yii\helpers\ArrayHelper::map(\app\modules\admin\models\Genre::find()->all(), 'name', 'name'),
        'theme' => Select2::THEME_BOOTSTRAP,
        'options' => ['placeholder' => 'Выберите жанр', 'multiple' => true, 'autocomplete' => 'off'],
        'pluginOptions' => [
            'allowClear' => true
        ],
    ]) ?>

    <?= $form->field($model, 'country')->widget(Select2::class, [
        'name' => 'country',
        'data' => \yii\helpers\ArrayHelper::map(\app\modules\admin\models\Country::find()->all(), 'name', 'name'),
        'theme' => Select2::THEME_BOOTSTRAP,
        'options' => ['placeholder' => 'Выберите страну', 'multiple' => true, 'autocomplete' => 'off'],
        'pluginOptions' => [
            'allowClear' => true
        ],
    ]) ?>

    <?= $form->field($model, 'duration')->widget(\yii\widgets\MaskedInput::class, [
        'mask' => 'h:m',
        'definitions'=>[
            'h'=>[
                'cardinality'=>2,
                'prevalidator' => [
                    ['validator'=>'^([0-2])$', 'cardinality'=>1],
                    ['validator'=>'^([0-9]|0[0-9]|1[0-9]|2[0-3])$', 'cardinality'=>2],
                ],
                'validator'=>'^([0-9]|0[0-9]|1[0-9]|2[0-3])$'
            ],
            'm'=>[
                'cardinality'=>2,
                'prevalidator' => [
                    ['validator'=>'^(0|[0-5])$', 'cardinality'=>1],
                    ['validator'=>'^([0-5]?\d)$', 'cardinality'=>2],
                ]
            ]
        ], 'options' => ['class' => 'form-control form-masked-input']]) ?>

    <?= $form->field($model, 'director')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'actors')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'release_date')->widget(DatePicker::class, [
        'name' => 'release_date',
        'type' => DatePicker::TYPE_COMPONENT_APPEND,
        'readonly' => true,
        'pluginOptions' => [
            'todayHighlight' => true,
            'format' => 'yyyy-mm-dd',
            'autoclose' => true
        ]
    ]) ?>

    <?= $form->field($model, 'description')->textarea(['rows' => 6]) ?>

    <?= $form->field($model, 'status')->dropDownList([
        '0' => 'Скоро в прокате',
        '1' => 'В прокате',
        '2' => 'Завершен'
    ]) ?>

    <?= $form->field($model, 'poster')->widget(FileInput::class, [
        'options' => ['accept' => 'image/*'],
        'pluginOptions' => [
            'initialPreview' => $isUpdate ? $model->getPosterUrl() : '',
            'initialPreviewAsData' => true,
            'showUpload' => false,
            'allowedFileTypes' => ['image']
        ],
    ]) ?>

    <?= $form->field($model, 'movie_shots[]')->widget(FileInput::class, [
        'options' => [
            'multiple' => true,
            'accept' => 'image/*'
        ],
        'pluginOptions' => [
            'initialPreview' => $isUpdate ? $model->getMovieShotsUrl() : [],
            'initialPreviewAsData' => true,
            'initialPreviewConfig' => $isUpdate ? $model->getPreviewConfig() : [],
            'overwriteInitial' => false,
            'showUpload' => false,
            'deleteUrl' => \yii\helpers\Url::to(['movie/delete']),
            'allowedFileTypes' => ['image']
        ],
    ]) ?>

    <?= $form->field($model, 'trailer')->widget(FileInput::class, [
        'options' => ['accept' => 'video/*'],
        'pluginOptions' => [
            'initialPreview' => $isUpdate ? $model->getTrailerUrl() : '',
            'initialPreviewFileType'=> 'video',
            'initialPreviewAsData' => true,
            'initialPreviewConfig'=> [
                ['filetype'=> "video/mp4"],
                ['caption'=> $model->name ? $model->name : '']
            ],
            'allowedFileTypes' => ['video'],
            'allowedFileExtensions'=>['mp4'],
            'showUpload' => false
        ],
    ]) ?>

    <div class="form-group">
        <?= Html::submitButton('Сохранить', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

modules/admin/views/movie/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\modules\admin\models\MovieForm */

$this->title = 'Новый фильм';
$this->params['breadcrumbs'][] = ['label' => 'Фильмы', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="movie-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

modules/admin/views/movie/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use kartik\date\DatePicker;
use yii\widgets\Pjax;

/* @var $this yii\web\View */
/* @var $searchModel app\modules\admin\models\MovieSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Фильмы';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="movie-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Добавить фильм', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?php Pjax::begin(['id' => 'movies', 'enablePushState' => false]); ?>

        <?= GridView::widget([
            'dataProvider' => $dataProvider,
            'filterModel' => $searchModel,
            'columns' => [
                ['class' => 'yii\grid\SerialColumn'],

                'id',
                'name',
                'genre',
                'country',
                'duration',
                [
                    'attribute' => 'release_date',
                    'value' => function ($movie) {

                        return Yii::$app->formatter->asDate($movie->release_date, 'dd/MM/yyyy');
                    },
                    'filter' => DatePicker::widget([
                        'model' => $searchModel,
                        'readonly' => true,
                        'attribute' => 'release_date',
                        'type' => DatePicker::TYPE_COMPONENT_APPEND,
                        'pluginOptions' => [
                            'autoclose' => true,
                            'format' => 'yyyy-mm-dd',
                            'todayHighlight' => true,
                        ]
                    ]),
                ],
                [
                    'attribute' => 'status',
                    'value' => function ($show) {
                        if ($show->status == 0) {
                            return 'Скоро в прокате';
                        } elseif ($show->status == 1) {
                            return 'В прокате';
                        }
                        return 'Прокат завершен';
                    },
                    'filter' => Html::activeDropDownList(
                        $searchModel,
                        'status',
                        [
                            '0' => 'Скоро в прокате',
                            '1' => 'В прокате',
                            '2' => 'Прокат завершен'
                        ],
                        [
                            'class' => 'form-control',
                            'prompt' => 'Выбрать'
                        ]
                    ),
                    'headerOptions' => ['width' => '140'],
                ],

                [
                    'class' => 'yii\grid\ActionColumn',
                    'header' => 'Действия',
                    'template' => '{view} &nbsp {update}',
                    'headerOptions' => ['width' => '80'],
                ],
            ],
        ]); ?>

    <?php Pjax::end(); ?>

</div>

modules/admin/views/movie/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\modules\admin\models\MovieForm */

$this->title = 'Редактирование: ' . $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Фильмы', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Редактирование';
?>
<div class="movie-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
        'isUpdate' => true
    ]) ?>

</div>

modules/admin/views/movie/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\modules\admin\models\Movie */

$this->title = $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Фильмы', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="movie-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Редактировать', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?php
        if ($model->status == 1) {
            echo Html::a('Добавить киносеанс', ['show/create'], [
                'class' => 'btn btn-success',
                'data' => [
                    'method' => 'post',
                    'params' => ['movieID' => $model->id]
                ]
            ]);
        }
        ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'name',
            'genre',
            'country',
            'duration',
            'director',
            'actors',
            'release_date',
            'description:ntext',
            [
                'attribute' => 'status',
                'value' => function ($movie) {
                    if ($movie->status == 0) {
                        return 'Скоро в прокате';
                    } elseif ($movie->status == 1) {
                        return 'В прокате';
                    }
                    return 'Завершен';
                },
            ],
            [
                'label' => 'Постер',
                'value' => function ($movie) {
                    return Html::img("/{$movie->images_path}poster.jpg", ['width' => '200px']);
                },
                'format' => 'html',
            ],
            [
                'label' => 'Кадры из фильма',
                'value' => function ($movie) {
                    $path = $movie->images_path . 'movie_shots';
                    $images = \yii\helpers\FileHelper::findFiles($path);
                    $result = "";
                    foreach ($images as $image) {
                        $result .= "<img src=\"/$image\" style=\"width: 400px;\">";
                    }
                    return $result;
                },
                'format' => 'raw',
            ],
            [
                'label' => 'Трейлер',
                'value' => function ($movie) {
                    return '<video controls style="width: 400px;"><source src="/' . $movie->images_path . 'trailer.mp4" type="video/mp4"></video>';
                },
                'format' => 'raw',
            ]
        ],
    ]) ?>

    <?php
    $shows = [];

    foreach ($model->shows as $show) {
        if ($show->status == 0) {
            for ($i = 0; $i < 5; $i++) {
                $date = date('Y-m-d', strtotime("+$i day"));
                if ($show->date == $date) {
                    $shows[$date][] = $show;
                }
            }
        }
    }
    if ($shows) :
        ?>

        <h2>Киносеансы</h2>

        <?php foreach ($shows as $key => $day) : ?>
        <?php
        if ($key == date('Y-m-d'))  {
            echo '<span class="date ml-2">Сегодня, ' . date("d.m") . '</span><br>';
        } elseif ($key == date('Y-m-d', strtotime('+1 day'))) {
            echo '<span class="date ml-2">Завтра, ' . date("d.m", strtotime('+1 day')) . '</span><br>';
        } else {
            $date = DateTime::createFromFormat('Y-m-d', $key)->format('l, d.m');
            echo '<span class="date ml-2">' . $date . '</span><br>';
        }
        ?>
        <div class="row mt-2 pl-3 pr-3" style="margin: 10px 0;">
            <?php foreach ($day as $show) : ?>
                <a  class="col-xs-4 col-sm-4 col-md-3 show-btn" href = "<?= \yii\helpers\Url::to(['show/view', 'id' => $show->id]) ?>">
                    <span class="mx-auto"><?= DateTime::createFromFormat('H:i:s', $show->time)->format('H:i') ?></span><hr>
                    <span class="mx-auto"><?= $show->price ?></span>
                </a>
            <?php endforeach; ?>
        </div>

    <?php endforeach; ?>
    <?php endif; ?>
</div>

<?php
$this->registerCss("
        .show-btn {
            max-width: 90px;
            width: 75px;
            margin: 5px;
            height: 56px;
            padding: 5px 0;
            text-align: center;
            border-radius: 10px;
            background: #ffffff;
            border: 1px solid #7c7c7c;
            line-height: 24px;
            text-transform: none;
        }
        .show-btn hr {
            margin-top: 0;
            margin-bottom: 0;
            width: 80%;
            margin-left: 10%;
            border-top: 1px solid #a0a0a0;
        }
        .date {
            font-weight: 600;
        }
        .show-btn, .show-btn:hover {
            color: #000000;
        }
    ");
?>