models/Movie.php
<?php

namespace app\models;

/**
 * This is the model class for table "movies".
 *
 * @property int $id
 * @property string $name
 * @property string $genre
 * @property string $country
 * @property string $duration
 * @property string $director
 * @property string|null $actors
 * @property string $release_date
 * @property string $description
 * @property int $status
 * @property string $images_path
 *
 * @property Show[] $shows
 */
class Movie extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'movies';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['name', 'genre', 'country', 'duration', 'director', 'release_date', 'description', 'status', 'images_path'], 'required'],
            [['description'], 'string'],
            [['status'], 'integer'],
            [['name', 'country', 'director'], 'string', 'max' => 45],
            [['genre', 'actors', 'images_path'], 'string', 'max' => 100],
            [['duration'], 'string', 'max' => 5],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'Идентификатор',
            'name' => 'Название',
            'genre' => 'Жанр',
            'country' => 'Страна',
            'duration' => 'Длительность',
            'director' => 'Режиссер',
            'actors' => 'В ролях',
            'release_date' => 'Дата выхода',
            'description' => 'Описание',
            'status' => 'Статус',
            'images_path' => 'Путь к изображениям',
        ];
    }

    /**
     * Gets query for Shows.
     *
     * @return \yii\db\ActiveQuery
     */
    public function getShows()
    {
        return $this->hasMany(Show::class, ['movie_id' => 'id']);
    }

    public function getStringTime()
    {
        $time = explode(':', $this->duration);

        $hours = 'час';
        $minutes = 'минута';

        $remainder = ltrim($time[0], '0') % 10;

        if ($remainder == 0 || ($remainder >= 5 && $remainder <= 9) || ($time[0] >= 11 && $time[0] <= 19)) {
            $hours = 'часов';
        } else if ($remainder >= 2 && $remainder <= 4) {
            $hours = 'часа';
        }

        $remainder = $time[1] % 10;

        if ($remainder == 0 || ($remainder >= 5 && $remainder <= 9) || ($time[1] >= 11 && $time[1] <= 19)) {
            $minutes = 'минут';
        } else if ($remainder >= 2 && $remainder <= 4) {
            $minutes = 'минуты';
        }

        if ($time[0] == 0) {
            return $time[1] . ' ' . $minutes;
        }
        return ltrim($time[0], '0') . ' ' . $hours . ' ' . $time[1] . ' ' . $minutes;
    }
}

controllers/MovieController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Movie;
use app\models\MovieSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;

/**
 * MovieController implements the CRUD actions for Movie model.
 */
class MovieController extends Controller
{
    /**
     * Lists all Movie models.
     * @param null $status
     * @return string
     */
    public function actionIndex($status = null)
    {
        $searchModel = new MovieSearch();
        $params = Yii::$app->request->queryParams;
        if (is_null($status)) {
            $status = 'now';
        }
        $status == 'now' ? ($params['MovieSearch']['status'] = 1) : ($params['MovieSearch']['status'] = 0);
        unset($params['status']);

        $dataProvider = $searchModel->search($params);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
            'status' => $status
        ]);
    }

    /**
     * Displays a single Movie model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'movie' => $this->findModel($id)
        ]);
    }

    /**
     * Finds the Movie model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Movie
     * @throws NotFoundHttpException
     */
    protected function findModel($id)
    {
        if (($model = Movie::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('Страница не найдена.');
    }
}

views/movie/_movie.php
<?php  

use yii\helpers\Url;

/* @var $model app\models\Movie */

?>

<a class="poster" href="<?= Url::to(['movie/view', 'id' => $model->id]) ?>">
   <img class="col" src="/<?= $model->images_path ?>poster.jpg">
    <?php if ($model->status == 0) : ?>
        <div class="date mx-auto justify-content-center">
            <?php
                $date = DateTime::createFromFormat('Y-m-d', $model->release_date)->format('d.m');
                echo $date;
            ?>
        </div>
    <?php endif; ?>
</a>

views/movie/index.php
<?php

use app\assets\MovieAsset;
use yii\widgets\ListView;
use yii\widgets\Pjax;
use yii\helpers\Url;
use yii\helpers\Html;

/* @var $status string */
/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

MovieAsset::register($this);

$this->title = 'Фильмы';
?>
<div class="mb-5 container">
    <?php Pjax::begin(); ?>
    <div class="row mx-auto justify-content-center">
        <?= Html::a('В прокате', Url::to(['movie/index', 'status' => 'now']), ['class' => 'btn btn-outline-light']) ?>
        <?= Html::a('Скоро', Url::to(['movie/index', 'status' => 'soon']), ['class' => 'btn btn-outline-light']) ?>
        <h1 class="col-12 mt-4"><?= $status == 'now' ? 'Сейчас в прокате' : 'Скоро в кино' ?></h1>
            <?=
            ListView::widget([
                'dataProvider' => $dataProvider,
                'itemView' => '_movie',
                'summary' => '',
                'itemOptions' => [
                    'class' => 'mt-4 col-xs-4 col-sm-4 col-md-3 item',
                ]
            ]);
            ?>
    </div>
    <?php Pjax::end(); ?>
</div>

views/movie/view.php
<?php

use app\assets\MovieViewAsset;
use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $movie app\models\Movie */

$this->title = $movie->name;

\yii\web\YiiAsset::register($this);
MovieViewAsset::register($this);

$shows = [];

foreach ($movie->shows as $show) {
    if ($show->status == 0) {
        for ($i = 0; $i < 5; $i++) {
            $date = date('Y-m-d', strtotime("+$i day"));
            if ($show->date == $date) {
                $shows[$date][] = $show;
            }
        }
    }
}
?>

<div class="container pt-1">
    <div class="row mb-4 mx-auto justify-content-center">
        <div class="col-md-6 col-sm-12 trailer">
            <h5 class="name" style="font-weight: 600; text-indent: 0.5em; text-align: justify;"><?= $movie->name ?></h5>

            <iframe class="mt-2 embed-responsive-item" src="/<?= $movie->images_path ?>trailer.mp4" frameborder="0" allow="accelerometer; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        </div>
        <div class="col-md-4 col-sm-12 mt-5 label">
            <div class="information mb-3">
                <span class="title">Время фильма</span><hr>
                <span class="text"><?= $movie->getStringTime() ?></span>
            </div>
            <div class="information mb-3">
                <span class="title">Страна</span><hr>
                <span class="text"><?= $movie->country ?></span>
            </div>
            <div class="information mb-3">
                <span class="title">Жанр</span><hr>
                <span class="text"><?= $movie->genre ?></span>
            </div>
            <div class="information mb-3">
                <span class="title">Режиссер</span><hr>
                <span class="text"><?= $movie->director ?></span>
            </div>
            <?php if (!empty($movie->actors)) : ?>
            <div class="information mb-3">
                <span class="title">Актеры</span><hr>
                <span class="text">
                    <?php
                        $actors = explode(',', $movie->actors);

                        $result = $actors[0];
                        foreach ($actors as $key => $actor) {
                            if ($key == 0) {
                                continue;
                            }
                            $result .= ',<br>' . $actor;
                        }
                        echo $result;
                    ?>
                </span>
            </div>
            <?php endif; ?>
        </div>
    </div>
</div>
<div class="container mb-3 tickets-container">
    <div class="shedul">
        <?php if ($shows) : ?>
            <h4>Расписание сеансов</h4>
            <?php foreach ($shows as $key => $day) : ?>
                <?php
                    if ($key == date('Y-m-d'))  {
                        echo '<span class="date ml-2">Сегодня, ' . date("d.m") . '</span><br>';
                    } elseif ($key == date('Y-m-d', strtotime('+1 day'))) {
                        echo '<span class="date ml-2">Завтра, ' . date("d.m", strtotime('+1 day')) . '</span><br>';
                    } else {
                        $date = DateTime::createFromFormat('Y-m-d', $key)->format('l, d.m');
                        echo '<span class="date ml-2">' . $date . '</span><br>';
                    }
                ?>
                <div class="row mt-2 pl-3 pr-3 tickets">
                    <?php foreach ($day as $show) : ?>
                    <button type="button"  class="col-xs-4 col-sm-4 col-md-3 ticket" value = "<?= $show->id ?>" data-toggle="collapse" href="#collapseHall" role="button" aria-expanded="false" aria-controls="collapseHall">
                        <span class="mx-auto"><?= DateTime::createFromFormat('H:i:s', $show->time)->format('H:i') ?></span><hr>
                        <span class="mx-auto"><?= $show->price ?></span>
                    </button>
                    <?php endforeach; ?>
                </div>

            <?php endforeach; ?>

        <?php endif; ?>
    </div>
</div>
<div class="description mb-4">
    <span>
        <?= $movie->description ?>
    </span>
    
    <div class="photos mt-4">
        <div id="photos" class="carousel slide" data-ride="carousel">
            <div class="carousel-inner">
                <?php
                    $number = 0;
                    
                    $path = $movie->images_path . 'movie_shots';
                    $images = \yii\helpers\FileHelper::findFiles($path);
                ?>
                <?php foreach ($images as $image) : ?>
                        <div class="carousel-item <?php if ($number == 0) { $number++; echo 'active'; } ?>">
                            <?= Html::img('/' . $image, ['class' => 'd-block w-100']); ?>
                        </div>
                 <?php endforeach; ?>
            </div>

            <a class="left carousel-control" href="#photos" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left"></span>
            </a>
            <a class="right carousel-control" href="#photos" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right mr-5"></span>
            </a>
        </div>
    </div>
</div>

<div class="container-fluid collapse container-hall" id="collapseHall">
    <button type="button" class="btn btn-dark" aria-label="Close" data-toggle="collapse" href="#collapseHall" role="button" aria-expanded="false" aria-controls="collapseHall">
        <span aria-hidden="true">&times;</span>
    </button>
    <div class="container hall overflow-auto"></div>
</div>